# Form implementation generated from reading ui file '_checkbox.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 340)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(79, 211, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 60, 111, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbCinema = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.cbCinema.setObjectName("cbCinema")
        self.verticalLayout.addWidget(self.cbCinema)
        self.cbReadabook = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.cbReadabook.setObjectName("cbReadabook")
        self.verticalLayout.addWidget(self.cbReadabook)
        self.cbSport = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.cbSport.setObjectName("cbSport")
        self.verticalLayout.addWidget(self.cbSport)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 70, 181, 91))
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Take the Choosing"))
        self.cbCinema.setText(_translate("MainWindow", "Cinema"))
        self.cbReadabook.setText(_translate("MainWindow", "Read a Book"))
        self.cbSport.setText(_translate("MainWindow", "Sport"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
