# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 364)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 58, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 58, 21))
        self.label_2.setObjectName("label_2")
        self.txt_number1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_number1.setGeometry(QtCore.QRect(180, 50, 161, 21))
        self.txt_number1.setObjectName("txt_number1")
        self.txt_number2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_number2.setGeometry(QtCore.QRect(180, 100, 161, 21))
        self.txt_number2.setObjectName("txt_number2")
        self.btn_Sumup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Sumup.setGeometry(QtCore.QRect(80, 150, 100, 41))
        self.btn_Sumup.setObjectName("btn_Sumup")
        self.btn_substraction = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_substraction.setGeometry(QtCore.QRect(210, 150, 100, 41))
        self.btn_substraction.setObjectName("btn_substraction")
        self.btn_division = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_division.setGeometry(QtCore.QRect(340, 150, 100, 41))
        self.btn_division.setObjectName("btn_division")
        self.btn_multiplication = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_multiplication.setGeometry(QtCore.QRect(470, 150, 100, 41))
        self.btn_multiplication.setObjectName("btn_multiplication")
        self.lbl_result = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(130, 210, 161, 31))
        self.lbl_result.setObjectName("lbl_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 615, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Number 1 "))
        self.label_2.setText(_translate("MainWindow", "Number 2"))
        self.btn_Sumup.setText(_translate("MainWindow", "Sum up"))
        self.btn_substraction.setText(_translate("MainWindow", "Substraction"))
        self.btn_division.setText(_translate("MainWindow", "Division"))
        self.btn_multiplication.setText(_translate("MainWindow", "Multiplication"))
        self.lbl_result.setText(_translate("MainWindow", "Result: "))
